### PR TITLE
Bump asmjit/asmtk to latest version

### PR DESCRIPTION
**Pull request by pmeerw**
slightly adjust internal implementation to work with latest asmjit
add small test program to load asmjit.dll or XEDParse.dll, both exposing the XEDParseAssemble() interface
add brief README

### CODE REVIEW

**Comment by pmeerw** [comment]
I've compiled with Visual Studio 2019 (16.11.19) and installed "C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]"

**Comment by mrexodia** [comment]
I think you have to update the `image` to either `Visual Studio 2017` or `Visual Studio 2019` and that should fix it.

**Comment by pmeerw** [comment]
@mrexodia "The build tools for v141_xp (Platform Toolset = 'v141_xp') cannot be found. To build using the v141_xp build tools, please install v141_xp build tools."

that can be manually selected for VS 2019 (which I did locally):  install "C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]"

I have no idea how this appveyor works, probably it works out-of-the-box with VS 2013 or 2015 images?

**Comment by mrexodia** [comment]
I'll switch to GitHub Actions, according to https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#workloads-components-and-extensions that should have the XP toolset installed.

Thanks!

**Pull request merged**
